name: generate animation
'on':
  schedule:
    - cron: 0 */24 * * *
  workflow_dispatch: null
jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: '${{ github.repository_owner }}'
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
