name: Generate snk

on:
  schedule:
    - cron: "0 */24 * * *"
  
  workflow_dispatch:

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Generate SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/ctp-snk.svg?color_snake=#cba6f7&color_dots=#313244,#6c7086,#9399b2,#b4befe,#cba6f7&color_progress=#cba6f7
            
      - name: Push SVG to target branch
        uses: crazy-max/ghaction-github-pages@v4.2.0
        with:
          target_branch: snake
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
