name: Update stats.fm Top Albums

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Update stats.fm top albums
        uses: teraha-dev/statsfm-to-markdown@v1.1.0
        with:
          statsfm_username: 'om3ga6400'

          display_limit: '28'       # Number of albums to show (max 50)
          time_range: 'weeks'       # Data period: weeks, months, lifetime
          show_rank: 'true'         # Include rank number in tooltip: true, false
          show_duration: 'true'     # Include playtime in tooltip: true, false
          readme_path: 'README.md'  # Path to your README file
          items_per_row: '7'        # Number of albums to display per row

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "statsfm-to-markdown Action"
          git add README.md # Or use the specific path from 'readme_path' if changed
          # Commit only if README.md has changed
          if git diff --staged --quiet; then
            echo "No changes in README.md. Skipping commit."
          else
            git commit -m "docs: Update stats.fm top albums"
            echo "Pushing changes..."
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
