name: Update stats.fm Top Albums

on:
  schedule:
    - cron: "0 0,12 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Update stats.fm top albums
        uses: teraha-dev/statsfm-to-markdown@v1.1.1
        with:
          statsfm_username: 'om3ga6400'

          display_limit: '12'       # Number of albums to show (max 50)
          time_range: 'weeks'       # Data period: weeks, months, lifetime
          show_rank: 'true'         # Include rank number in SVG: true, false
          show_duration: 'true'     # Include playtime in SVG: true, false
          readme_path: 'README.md'  # Path to your README file
          items_per_row: '6'        # Number of albums to display per row
          theme: 'dark'             # Theme for album cards: light, dark

      # Commit and push the updated README file
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "statsfm-to-markdown Action"
          # Add README and SVG files
          git add README.md statsfm_svgs/
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit."
            exit 0
          else
            git commit -m "docs: Update stats.fm top albums"
            echo "Pushing changes..."
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required for pushing changes
