name: Update stats.fm Top Albums

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update stats.fm top albums
        uses: teraha-dev/statsfm-to-markdown@v1.0.0
        with:
          statsfm_username: 'om3ga6400'
          display_limit: 10
          

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "statsfm-to-markdown Action"
          git add README.md
          if git diff --staged --quiet; then
            echo "No changes in README.md. Skipping commit."
          else
            git commit -m "docs: Update stats.fm top albums"
            echo "Pushing changes..."
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
